### ISSUE TITLE
add Gimp badge in software section

### ISSUE THREAD

**Issue by carafelix** [rahuldkjain/github-profile-readme-generator#731] opened 2023-06-24 02:31 UTC
Gimp is a nice open-source alternative to Photoshop or similar image manipulation tools. 
Adding it to the badge collection would be a nice touch nice, for ex, I use it all the time.

**Comment by AshkanArabim** [comment] 2023-09-27 17:00
I'm interested in tackling this issue. Could this be assigned to me?

**Closed** 2024-02-27 16:11 UTC
Labels: enhancement, hacktoberfest

**Comment by AshkanArabim** [comment] 2024-02-27 17:25
Okay just so I know what's going on, should I do anything or not? The issue is marked as completed.

**Comment by g-savitha** [comment] 2024-03-01 16:15
Someone has fixed it.
